name: Vercel Preview Environment

description: Deploy Vercel preview environments per pull request, integrate with external services smoothly

inputs:
  delete:
    description: Delete the preview related data on Vercel
    required: false
    type: boolean
    default: false
  env:
    description: Environment variables to create on Vercel, they are scoped to the "preview" environment and the current branch
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Setup
      shell: bash
      run: node --experimental-fetch --no-warnings ${{ github.action_path }}/scripts/setup.mjs

    - if: ${{ inputs.delete == 'false' }}
      name: Deploy
      shell: bash
      env:
        VERCEL_PREVIEW_ENV: ${{ inputs.env }}
      run: node --experimental-fetch --no-warnings ${{ github.action_path }}/scripts/deploy.mjs

    - if: ${{ inputs.delete == 'true' }}
      name: Delete
      shell: bash
      run: node --experimental-fetch --no-warnings ${{ github.action_path }}/scripts/delete.mjs
