name: Vercel Preview Environment

inputs:
  delete:
    description: Delete the preview related data on Vercel
    required: false
    type: boolean
    default: false
  env-preview-prefix:
    description: Prefix to detect environment variables to create on Vercel
    required: false
    type: string
    default: VERCEL_PREVIEW_

runs:
  using: composite
  steps:
    - name: Setup
      shell: bash
      run: node --experimental-fetch --no-warnings ${{ github.action_path }}/scripts/setup.mjs

    - if: ${{ inputs.delete == 'false' }}
      name: Deploy
      shell: bash
      env:
        ENV_PREVIEW_PREFIX: ${{ inputs.env-preview-prefix }}
      run: node --experimental-fetch --no-warnings ${{ github.action_path }}/scripts/deploy.mjs

    - if: ${{ inputs.delete == 'true' }}
      name: Delete
      shell: bash
      run: node --experimental-fetch --no-warnings ${{ github.action_path }}/scripts/delete.mjs
